// === e-META script.js v3.4 ===
// Multilingue + placeholders dynamiques + responsive

const translations = {
  fr: {
    home: "Accueil",
    about: "À propos",
    faq: "FAQ",
    contact: "Contact",
    hero_title: "L’assistant IA pluridisciplinaire",
    hero_subtitle: "Formulaire intelligent pour analyser, diagnostiquer et recommander des solutions adaptées.",
    form_title: "Requête personnalisée",
    domain_label: "Domaine / Thème",
    choose_domain: "— Choisir —",
    domain_agriculture: "Agriculture",
    domain_finance: "Finance",
    domain_energy: "Énergie",
    domain_tech: "Technologie",
    domain_education: "Éducation",
    domain_health: "Santé",
    domain_commerce: "Commerce",
    domain_transport: "Transport",
    expected_label: "Résultat attendu",
    expected_placeholder: "Ex : Dossier de financement, plan stratégique...",
    budget_label: "Budget indicatif",
    budget_placeholder: "Montant estimé",
    currency_label: "Devise",
    name_label: "Nom complet",
    name_placeholder: "Votre nom complet",
    phone_label: "Téléphone (WhatsApp)",
    phone_placeholder: "+221...",
    details_label: "Détails / Contexte",
    details_placeholder: "Décrivez le contexte...",
    delivery_label: "Mode de restitution",
    delivery_whatsapp: "WhatsApp",
    delivery_email: "Email",
    delivery_display: "Affichage direct",
    submit_btn: "Envoyer la requête",
    reset_btn: "Réinitialiser",
    about_title: "À propos",
    about_text: "e-META structure les demandes et produit une synthèse stratégique adaptée au contexte.",
    faq_title: "FAQ",
    faq_q1: "Comment fonctionne e-META ?",
    faq_a1: "e-META analyse votre requête via l’IA et génère une synthèse personnalisée selon le contexte et vos attentes.",
    contact_title: "Contact",
    footer_slogan: "Simplement. Intelligemment."
  },
  en: {
    home: "Home",
    about: "About",
    faq: "FAQ",
    contact: "Contact",
    hero_title: "The multidisciplinary AI assistant",
    hero_subtitle: "Smart form to analyze, diagnose, and recommend tailored solutions.",
    form_title: "Custom Request",
    domain_label: "Domain / Topic",
    choose_domain: "— Choose —",
    domain_agriculture: "Agriculture",
    domain_finance: "Finance",
    domain_energy: "Energy",
    domain_tech: "Technology",
    domain_education: "Education",
    domain_health: "Health",
    domain_commerce: "Commerce",
    domain_transport: "Transport",
    expected_label: "Expected result",
    expected_placeholder: "Ex: Funding file, strategic plan...",
    budget_label: "Indicative budget",
    budget_placeholder: "Estimated amount",
    currency_label: "Currency",
    name_label: "Full name",
    name_placeholder: "Your full name",
    phone_label: "Phone (WhatsApp)",
    phone_placeholder: "+221...",
    details_label: "Details / Context",
    details_placeholder: "Describe the context...",
    delivery_label: "Delivery mode",
    delivery_whatsapp: "WhatsApp",
    delivery_email: "Email",
    delivery_display: "Direct display",
    submit_btn: "Send request",
    reset_btn: "Reset",
    about_title: "About",
    about_text: "e-META structures requests and provides strategic summaries adapted to context.",
    faq_title: "FAQ",
    faq_q1: "How does e-META work?",
    faq_a1: "e-META uses AI to analyze your request and deliver a strategic summary tailored to your needs.",
    contact_title: "Contact",
    footer_slogan: "Simply. Intelligently."
  },
  es: {
    home: "Inicio",
    about: "Acerca de",
    faq: "FAQ",
    contact: "Contacto",
    hero_title: "El asistente de IA multidisciplinario",
    hero_subtitle: "Formulario inteligente para analizar, diagnosticar y recomendar soluciones adaptadas.",
    form_title: "Solicitud personalizada",
    domain_label: "Dominio / Tema",
    choose_domain: "— Elegir —",
    domain_agriculture: "Agricultura",
    domain_finance: "Finanzas",
    domain_energy: "Energía",
    domain_tech: "Tecnología",
    domain_education: "Educación",
    domain_health: "Salud",
    domain_commerce: "Comercio",
    domain_transport: "Transporte",
    expected_label: "Resultado esperado",
    expected_placeholder: "Ej: Dossier de financiamiento...",
    budget_label: "Presupuesto indicativo",
    budget_placeholder: "Monto estimado",
    currency_label: "Moneda",
    name_label: "Nombre completo",
    name_placeholder: "Tu nombre completo",
    phone_label: "Teléfono (WhatsApp)",
    phone_placeholder: "+34...",
    details_label: "Detalles / Contexto",
    details_placeholder: "Describe el contexto...",
    delivery_label: "Modo de entrega",
    delivery_whatsapp: "WhatsApp",
    delivery_email: "Correo",
    delivery_display: "Visualización directa",
    submit_btn: "Enviar solicitud",
    reset_btn: "Restablecer",
    about_title: "Acerca de",
    about_text: "e-META estructura las solicitudes y produce un resumen estratégico adaptado al contexto.",
    faq_title: "FAQ",
    faq_q1: "¿Cómo funciona e-META?",
    faq_a1: "e-META analiza tu solicitud mediante IA y genera una síntesis personalizada según el contexto y tus objetivos.",
    contact_title: "Contacto",
    footer_slogan: "Simplemente. Inteligentemente."
  },
  ar: {
    home: "الرئيسية",
    about: "حول",
    faq: "الأسئلة الشائعة",
    contact: "اتصال",
    hero_title: "المساعد الذكي المتعدد المجالات",
    hero_subtitle: "نموذج ذكي لتحليل وتشخيص وتوصية بحلول مخصصة.",
    form_title: "طلب مخصص",
    domain_label: "المجال / الموضوع",
    choose_domain: "— اختر —",
    domain_agriculture: "الزراعة",
    domain_finance: "التمويل",
    domain_energy: "الطاقة",
    domain_tech: "التكنولوجيا",
    domain_education: "التعليم",
    domain_health: "الصحة",
    domain_commerce: "التجارة",
    domain_transport: "النقل",
    expected_label: "النتيجة المتوقعة",
    expected_placeholder: "مثلاً: ملف تمويل أو خطة استراتيجية...",
    budget_label: "الميزانية التقديرية",
    budget_placeholder: "المبلغ المقدر",
    currency_label: "العملة",
    name_label
